# 自動レビュアー割り当て設定
#
# 使い方:
# - reviewers: レビュアー候補のユーザー名リスト
# - numberOfReviewers: 割り当てるレビュアー数
# - addAssignees: 担当者も割り当てるか

# レビュアー設定
addReviewers: true
addAssignees: true

# レビュアー候補（ユーザー名を変更してください）
reviewers:
  # - username1
  # - username2

# 割り当てるレビュアー数
numberOfReviewers: 1

# PR作成者をレビュアーから除外
filterReviewersByLabels: false
skipTeamReviewers: false

# 担当者設定（オプション）
# assignees:
#   - username1

# ラベルベースのルーティング（オプション）
# reviewGroups:
#   frontend:
#     - frontend-reviewer1
#     - frontend-reviewer2
#   backend:
#     - backend-reviewer1
