#!/bin/bash
# multi-claude-setup.sh
# 
# 複数のClaude Codeを並列で起動するためのセットアップスクリプト
# WSL2 + tmux環境で使用
#
# 使用方法:
#   ./scripts/multi-claude-setup.sh [プロジェクト名] [ワーカー数]
#   例: ./scripts/multi-claude-setup.sh my-project 3

set -e

# === 設定 ===
PROJECT_NAME="${1:-$(basename $(pwd))}"
WORKER_COUNT="${2:-3}"
SESSION_NAME="${PROJECT_NAME}-dev"

# === 色付き出力 ===
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

log_info() { echo -e "${GREEN}[INFO]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

# === 前提条件チェック ===
check_requirements() {
    log_info "前提条件をチェック中..."
    
    if ! command -v tmux &> /dev/null; then
        log_error "tmuxがインストールされていません"
        echo "  インストール: sudo apt install tmux -y"
        exit 1
    fi
    
    if ! command -v git &> /dev/null; then
        log_error "gitがインストールされていません"
        exit 1
    fi
    
    if ! command -v claude &> /dev/null; then
        log_error "Claude Codeがインストールされていません"
        echo "  インストール: npm install -g @anthropic-ai/claude-code"
        exit 1
    fi
    
    log_info "✓ 前提条件OK"
}

# === 初期コミット確認 ===
ensure_initial_commit() {
    log_info "Gitリポジトリの状態を確認中..."
    
    # Gitリポジトリかどうか確認
    if ! git rev-parse --is-inside-work-tree &> /dev/null; then
        log_error "Gitリポジトリではありません。先に 'git init' を実行してください。"
        exit 1
    fi
    
    # コミットが存在するか確認
    if ! git rev-parse HEAD &> /dev/null 2>&1; then
        log_warn "初期コミットがありません。自動で作成します..."
        git add .
        git commit -m "chore: Initial commit (auto-generated by multi-claude-setup)"
        log_info "✓ 初期コミット作成完了"
    else
        log_info "✓ Gitリポジトリ確認OK"
    fi
}

# === ワーカーブランチ作成 ===
create_worker_branches() {
    log_info "ワーカーブランチを作成中..."
    
    for i in $(seq 1 $WORKER_COUNT); do
        BRANCH_NAME="feature/worker-$i"
        if git show-ref --verify --quiet refs/heads/$BRANCH_NAME; then
            log_warn "ブランチ $BRANCH_NAME は既に存在します"
        else
            git branch $BRANCH_NAME
            log_info "✓ ブランチ作成: $BRANCH_NAME"
        fi
    done
}

# === Worktree作成 ===
create_worktrees() {
    log_info "Worktreeを作成中..."
    
    PARENT_DIR=$(dirname $(pwd))
    
    for i in $(seq 1 $WORKER_COUNT); do
        WORKTREE_DIR="$PARENT_DIR/${PROJECT_NAME}-worker-$i"
        BRANCH_NAME="feature/worker-$i"
        
        if [ -d "$WORKTREE_DIR" ]; then
            log_warn "Worktree $WORKTREE_DIR は既に存在します"
        else
            git worktree add "$WORKTREE_DIR" $BRANCH_NAME
            log_info "✓ Worktree作成: $WORKTREE_DIR"
        fi
    done
}

# === tmuxセッション作成 ===
create_tmux_session() {
    log_info "tmuxセッションを作成中..."
    
    # 既存セッションを削除
    tmux kill-session -t $SESSION_NAME 2>/dev/null || true
    
    # 新しいセッションを作成（最初のペインはmainディレクトリ）
    tmux new-session -d -s $SESSION_NAME -c "$(pwd)"
    
    PARENT_DIR=$(dirname $(pwd))
    
    # ワーカー用のペインを追加
    for i in $(seq 1 $WORKER_COUNT); do
        WORKTREE_DIR="$PARENT_DIR/${PROJECT_NAME}-worker-$i"
        
        if [ $i -le 2 ]; then
            # 最初の2つは縦分割
            tmux split-window -h -t $SESSION_NAME -c "$WORKTREE_DIR"
        else
            # 3つ目以降は横分割
            tmux split-window -v -t $SESSION_NAME -c "$WORKTREE_DIR"
        fi
    done
    
    # レイアウトを均等に調整
    tmux select-layout -t $SESSION_NAME tiled
    
    log_info "✓ tmuxセッション作成: $SESSION_NAME"
}

# === 各ペインでClaude Code起動 ===
start_claude_in_panes() {
    log_info "各ペインでClaude Codeを起動中..."
    
    # メインペイン（PM/統合役）
    tmux send-keys -t $SESSION_NAME:0.0 "echo '=== PM/統合役 (main) ===' && claude" C-m
    
    PARENT_DIR=$(dirname $(pwd))
    
    # ワーカーペイン
    for i in $(seq 1 $WORKER_COUNT); do
        tmux send-keys -t $SESSION_NAME:0.$i "echo '=== Worker $i ===' && claude" C-m
    done
    
    log_info "✓ Claude Code起動完了"
}

# === 使い方表示 ===
show_usage() {
    echo ""
    echo "=========================================="
    echo " 並列Claude開発環境がセットアップされました"
    echo "=========================================="
    echo ""
    echo "セッションにアタッチ:"
    echo "  tmux attach -t $SESSION_NAME"
    echo ""
    echo "tmux操作:"
    echo "  Ctrl+b 矢印キー  : ペイン移動"
    echo "  Ctrl+b d         : セッション切断（バックグラウンド）"
    echo "  Ctrl+b z         : ペイン最大化/復元"
    echo ""
    echo "Worktree一覧:"
    git worktree list
    echo ""
}

# === クリーンアップ ===
cleanup() {
    log_info "クリーンアップ中..."
    
    PARENT_DIR=$(dirname $(pwd))
    
    for i in $(seq 1 $WORKER_COUNT); do
        WORKTREE_DIR="$PARENT_DIR/${PROJECT_NAME}-worker-$i"
        BRANCH_NAME="feature/worker-$i"
        
        if [ -d "$WORKTREE_DIR" ]; then
            git worktree remove "$WORKTREE_DIR" --force 2>/dev/null || true
            log_info "✓ Worktree削除: $WORKTREE_DIR"
        fi
        
        if git show-ref --verify --quiet refs/heads/$BRANCH_NAME; then
            git branch -D $BRANCH_NAME 2>/dev/null || true
            log_info "✓ ブランチ削除: $BRANCH_NAME"
        fi
    done
    
    tmux kill-session -t $SESSION_NAME 2>/dev/null || true
    log_info "✓ tmuxセッション削除: $SESSION_NAME"
    
    log_info "クリーンアップ完了"
}

# === メイン処理 ===
main() {
    echo ""
    echo "=========================================="
    echo " Multi-Claude Setup Script"
    echo " プロジェクト: $PROJECT_NAME"
    echo " ワーカー数: $WORKER_COUNT"
    echo "=========================================="
    echo ""
    
    check_requirements
    ensure_initial_commit
    create_worker_branches
    create_worktrees
    create_tmux_session
    start_claude_in_panes
    show_usage
    
    # セッションにアタッチ
    tmux attach -t $SESSION_NAME
}

# === コマンドライン引数処理 ===
case "${1:-}" in
    --cleanup|-c)
        PROJECT_NAME="${2:-$(basename $(pwd))}"
        WORKER_COUNT="${3:-3}"
        cleanup
        ;;
    --help|-h)
        echo "使用方法:"
        echo "  $0 [プロジェクト名] [ワーカー数]  - セットアップ実行"
        echo "  $0 --cleanup [プロジェクト名]    - クリーンアップ"
        echo "  $0 --help                        - ヘルプ表示"
        ;;
    *)
        main
        ;;
esac
